import { readFile, writeFile, access, mkdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { build } from 'esbuild';
import vm from 'node:vm';
for (const file of ['index.html','styles.css','app.js','world.js','animals.js','child.js','foil.js','audio.js','vendor/three.module.js','vendor/three.core.js','assets/cover.png']) await access('dist/'+file);
for (const file of ['app.js','world.js','animals.js','child.js','foil.js','audio.js']) execFileSync(process.execPath,['--check','dist/'+file]);
let html=await readFile('dist/index.html','utf8');
for(const [,file] of html.matchAll(/(?:src|href)="(\.\/[^\"]+)"/g)) await access('dist/'+file.slice(2));
const bundle=await build({entryPoints:['dist/app.js'],bundle:true,write:false,minify:true,format:'iife',target:'es2022',alias:{three:'./dist/vendor/three.module.js'},legalComments:'inline'});
const image=(await readFile('dist/assets/cover.png')).toString('base64');
const js=bundle.outputFiles[0].text.replaceAll('./assets/cover.png','data:image/png;base64,'+image).replaceAll('</script','<\\/script');
const css=await readFile('dist/styles.css','utf8');
html=html.replace('<link rel="stylesheet" href="./styles.css" />',()=>`<style>${css}</style>`).replace(/\s*<script type="importmap">.*?<\/script>/s,'').replace('<script type="module" src="./app.js"></script>',()=>`<script>${js}</script>`);
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)];
if(scripts.length!==1)throw new Error('Expected one embedded application');
new vm.Script(scripts[0][1]);
if(/<script[^>]+src=|<link[^>]+rel="stylesheet"|@import/.test(html))throw new Error('Unembedded runtime dependency');
await mkdir('docs',{recursive:true});
await writeFile('docs/index.html',html);
await writeFile('docs/.nojekyll','');
console.log('Built docs/index.html — fully offline, with embedded Three.js, cover, styles, and audio.\nReady for GitHub Pages from the /docs folder.\nDevelopment preview: npm start');
